# Generated by Django 5.0.6 on 2024-06-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_foto'),
        ('galeria', '0007_alter_fotografia_publicada'),
    ]

    operations = [
    ]
